import Collection from "../../components/Collection/Collection";
import {fetchAPI} from '../../lib/api';
import Head from "next/head";
import { useContext, useEffect } from "react";
import {collectionContext} from "../../context/CollectionsContext";

export default function CollectionPage({collection,collections}) {
  
  const {collectionsValue,setCollections} = useContext(collectionContext);

  useEffect(()=>{
    setCollections(collections);
  },[])
  
  return (
    <>
      <Head>
        <title>{collection.attributes.title} – WoodHouse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../../favicon.png" />
      </Head>
      <Collection 
        name={collection.attributes.name} 
        image={collection.attributes.image} 
        desc={collection.attributes.desc}
        products={collection.attributes.products.data} 
        collections={collections}
      />
    </>
    
  )
}


export async function getStaticPaths() 
{
    let paths = await fetchAPI('/collections',{
        populate:['image','products','products.images'],
      });
    

    paths = paths.data.map((item)=>{
        return ({
            params:{
                name:item.attributes.name,
            }
        })
    })
    
    return {
      paths,
      fallback: false,
    };
}
  
  // `getStaticPaths` requires using `getStaticProps`
export async function getStaticProps({params}) 
{
    let collection = await fetchAPI(`/collections`,{
      populate:['image','products','products.images'],
        filters:{
          name:{
              $eq: params.name
          }
        }
      });
    
    collection=collection.data[0];
    
    let collections = await fetchAPI(`/collections`,{
      populate:'*',
    });
    
    collections=collections.data;
    
    return {
        // Passed to the page component as props
        props: { collection,collections },
    }
}