import Collection from "../../components/Collection/Collection";
import {fetchAPI} from '../../lib/api';
import Head from "next/head";

export default function AllPage({products,collections}) {
    return (
      <>
        <Head>
          <title>All Smoking Accessories & Home Objects  |  WoodHouse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="../../favicon.png" />
        </Head>
        <Collection 
          name={'all'} 
          image={'/images/all.jpg'} 
          desc={'Just to be clear when we say “All” we mean all the stuff we make, not all the stuff that exists on earth. There are other websites for that.'}
          products={products} 
          collections={collections}
        />
      </>
      
    )
  }
  
      
    // `getStaticPaths` requires using `getStaticProps`
  export async function getStaticProps() 
  {
      let collections = await fetchAPI(`/collections`,{
        populate:['image','products','products.images'],
        });
      
      collections=collections.data;
      
      let products = await fetchAPI(`/products`,{
        populate:'*'
      });
      
      products=products.data;
      
      return {
          // Passed to the page component as props
          props: { products,collections },
      }
  }