import Collection from "../../components/Collection/Collection";
import {fetchAPI} from '../../lib/api';
import Head from "next/head";
import { useContext, useEffect } from "react";
import {collectionContext} from "../../context/CollectionsContext";
import Layout from '../../components/Layout/Layout'

export default function AllPage({products,collections}) {
    
    const {setCollections} = useContext(collectionContext);

    useEffect(()=>{
      setCollections(collections);
    },[])

    return (
      <>
        <Head>
          <title>All Smoking Accessories & Home Objects  |  WoodHouse</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="../../favicon.png" />
        </Head>
        <Layout>
          <Collection 
            name={'all'} 
            image={'/images/all.jpg'} 
            desc={'Just to be clear when we say “All” we mean all the stuff we make, not all the stuff that exists on earth. There are other websites for that.'}
            products={products} 
            collections={collections}
          />
        </Layout>        
      </>
      
    )
  }
  
      
    // `getStaticPaths` requires using `getStaticProps`
  export async function getStaticProps() 
  {
      let collections = await fetchAPI(`/collections`,{
        populate:'*',
        sort:['id:asc']
        });
      
      collections=collections.data;
      
      let products = await fetchAPI(`/products`,{
        populate:'*',
      });
      
      products=products.data;
      
      return {
          // Passed to the page component as props
          props: { products,collections },revalidate: 10
      }
  }