import Head from 'next/head'
import Layout from '../components/Layout/Layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Smoking Accessories & Home Goods | WoodHouse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.png" />
      </Head>

    </div>
  )
}
