import Head from 'next/head'
import Home from '../components/Home/Home'
import {fetchAPI} from '../lib/api';

export default function HomePage({hero,favorites}) {
  return (
    <div>
      <Head>
        <title>Smoking Accessories & Home Goods | WoodHouse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.png" />
      </Head>
      <Home hero={hero} favorites={favorites}/>
    </div>
  )
}


export async function getStaticProps() {
  
  let hero = await fetchAPI('/heroes',{
    populate:['image','product','product.images']
  });

  hero = hero.data;
  
  
  let favorites = await fetchAPI('/favorite',{
    populate:['products','products.images']
  });

  favorites = favorites.data.attributes.products.data;

  return{
    props:{hero,favorites}
  }
}